# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-10 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='DNI')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=50)),
            ],
        ),
    ]
